# -*- coding: utf-8 -*-
"""
/***************************************************************************
 InclinometryWellsDialog
                                 A QGIS plugin
 InclinometryWells
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-17
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Shevchenko.AS
        email                : nastyashevchenkomail@mail.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic, QtWidgets
from qgis.core import QgsProject
from qgis.PyQt.QtCore import Qt

from .ui.tabSettings import TabSettings
from .ui.tabWellhead import TabWellhead
from .ui.tabInclinometry import TabInclinometry
from .ui.tabTarget import TabTarget


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'InclinometryWells_dialog_base.ui'),
    from_imports=True,
    import_from='InclinometryWells')


class InclinometryWellsDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(InclinometryWellsDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.setWindowFlag(Qt.WindowStaysOnTopHint, True)
        tabWellheads_index = self.tabWidget.indexOf(self.tabWellheads)
        self.tabWidget.setTabEnabled(tabWellheads_index, False)

        targets_index = self.tabWidget.indexOf(self.tabTargets)
        self.tabWidget.setTabEnabled(targets_index, False)

        incls_index = self.tabWidget.indexOf(self.tabIncls)
        self.tabWidget.setTabEnabled(incls_index, False)

        # =====================================================
        # Вкладка: Настройка
        # =====================================================

        self.tabSettings = TabSettings(self)
        # Источник слоёв — текущий проект QGIS
        self.tabSettingsWellheadMLCBox.setProject(QgsProject.instance())
        self.tabSettingsTargetsMLCBox.setProject(QgsProject.instance())
        self.tabSettingsBoresMLCBox.setProject(QgsProject.instance())

        # Применяем фильтры после установки проекта
        self.tabSettings.filterWellheadLayers()
        self.tabSettings.filterWelltargetLayers()
        self.tabSettings.filterWellboreLayers()

        # Если слои уже есть в проекте — выбираем их
        self.tabSettings.selectWellheadInComboBox()
        self.tabSettings.selectWelltargetInComboBox()
        self.tabSettings.selectWellboreInComboBox()

        # Повторная фильтрация при добавлении/удалении слоёв
        QgsProject.instance().layersAdded.connect(self.tabSettings._onLayersChanged)
        QgsProject.instance().layersRemoved.connect(self.tabSettings._onLayersChanged)

        # Подключаем кнопки
        self.tabSettingsWellheadBtn.clicked.connect(self.tabSettings.wellheadLayerAdd)
        self.tabSettingsTargetsBtn.clicked.connect(self.tabSettings.welltargetLayerAdd)
        self.tabSettingsBoresBtn.clicked.connect(self.tabSettings.wellboreLayerAdd)
        self.tabSettingsWellheadGoBtn.clicked.connect(self.tabSettings.wellheadTabActivate)

        # =====================================================
        # Вкладка: Позиция / Устье
        # =====================================================

        self.tabWellhead = TabWellhead(self)    
        # Подключаем сигнал на кнопку выбора позиции / устья
        self.btnSelectWellHead.clicked.connect( self.tabWellhead.selectWellHead )
        # Подключаем сигнал на кнопку смены системы координат
        self.mQgsProjectionSelectionWidgetWellHead.crsChanged.connect( self.tabWellhead.wellHeadCrsChanged )
        # Текущая система координат для расчетов
        self.crsOutputWellHead = self.tabWellhead.getCurrentCrs()
        self.tabWellheadInclGoBtn.clicked.connect(self.tabWellhead.inclTabActivate)
        # Добавляем новую позицию/устье в слой wellhead
        self.tabWellheadAdd.clicked.connect(self.tabWellhead.wellheadAdd)

        # =====================================================
        # Вкладка: Цели
        # =====================================================

        self.tabTarget = TabTarget(self)
        self.btnSelectTarget.clicked.connect(self.tabTarget.selectTarget)
        self.mQgsProjectionSelectionWidgetTarget.crsChanged.connect(self.tabTarget.targetCrsChanged)

        # =====================================================
        # Вкладка: Инклинометрия
        # =====================================================

        self.tabInclinometry = TabInclinometry(self)
        self.tabInclTargetGoBtn.clicked.connect(self.tabInclinometry.targetTabActivate)

